name: ibis-tutorial
channels:
  - conda-forge
dependencies:
  # runtime dependencies
  - ibis-duckdb >=9
  - ibis-bigquery >=9
  - ibis-polars >=9
  - jupyterlab >=4.2.0,<4.3
  - altair >=5.3.0,<5.4
  - plotnine >=0.13.5,<0.14
