[project]
name = "ibis-tutorial"
version = "0.1.0"
description = "Add a short description here"
authors = ["Gil Forsyth <gil@forsyth.dev>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
ibis-duckdb = ">=9.1,<9.2"
jupyterlab = ">=4.2.0,<4.3"
altair = ">=5.3.0,<5.4"
ibis-bigquery = ">=9.1,<9.2"
plotnine = ">=0.13.6,<0.14"
ibis-polars = ">=9.1,<9.2"
plotly = ">=5.22.0,<5.23"
